# Hypothesis Testing

The purpose of the test is to tell if there is any significant difference between two data sets.



## Overview

This module covers,

1) One sample and Two sample t-tests

2) ANOVA

3) Type I and Type II errors

4) Chi-Squared Tests

## Question 1 

*A student is trying to decide between two GPUs. He want to use the GPU for his research to run Deep learning algorithms, so the only thing he is concerned with is speed.*

*He picks a Deep Learning algorithm on a large data set and runs it on both GPUs 15 times, timing each run in hours. Results are given in the below lists GPU1 and GPU2.*

In [413]:
from scipy import stats
from scipy.stats import ttest_1samp
import numpy as np

In [414]:
GPU1 = np.array([11,9,10,11,10,12,9,11,12,9,11,12,9,10,9])
GPU2 = np.array([11,13,10,13,12,9,11,12,12,11,12,12,10,11,13])

#Assumption: Both the datasets (GPU1 & GPU 2) are random, independent, parametric & normally distributed

Hint: You can import ttest function from scipy to perform t tests 

**First T test**

*One sample t-test*

Check if the mean of the GPU1 is equal to zero.
- Null Hypothesis is that mean is equal to zero.
- Alternate hypothesis is that it is not equal to zero.

In [415]:
GPU1_mean = np.mean(GPU1)
print("Mean of GPU1 is: %5.2f" %(GPU1_mean))
print("Mean of GPU1 is not equal to Zero.")

Mean of GPU1 is: 10.33
Mean of GPU1 is not equal to Zero.


In [416]:
print("P-Value is : %5.16f"%ttest_1samp(GPU1, 0).pvalue)

P-Value is : 0.0000000000000072


In [417]:
print("Hence, we can reject the Null Hypothesis")

Hence, we can reject the Null Hypothesis


## Question 2

Given,

Null Hypothesis : There is no significant difference between data sets

Alternate Hypothesis : There is a significant difference

*Do two-sample testing and check whether to reject Null Hypothesis or not.*

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html

In [418]:
pval = stats.ttest_ind(GPU1,GPU2, equal_var=True).pvalue
pval

0.013794282041452725

In [419]:
print("P-value is observed to be %5.2f"%(pval))
print("Considering the threshold to be 5%")
print("%5.2f is less than %5.2f" %(pval, (5/100)))
print("Hence, we can Reject the Null Hypothesis")

P-value is observed to be  0.01
Considering the threshold to be 5%
 0.01 is less than  0.05
Hence, we can Reject the Null Hypothesis


## Question 3

He is trying a third GPU - GPU3.

In [420]:
GPU3 = np.array([9,10,9,11,10,13,12,9,12,12,13,12,13,10,11])

#Assumption: Both the datasets (GPU1 & GPU 3) are random, independent, parametric & normally distributed

*Do two-sample testing and check whether there is significant differene between speeds of two GPUs GPU1 and GPU3.*

#### Answer:

In [421]:
pval1_3 = stats.ttest_ind(GPU1, GPU3, equal_var=True).pvalue
pval1_3

0.14509210993138993

In [422]:
print("P-Value is observed to be %5.2f"%(pval1_3))
print("Considering the threshold to be 5%")
print("%5.2f is not less than %5.2f" %(pval1_3, (5/100)))
print("Hence, we cannot Reject the Null Hypothesis")

P-Value is observed to be  0.15
Considering the threshold to be 5%
 0.15 is not less than  0.05
Hence, we cannot Reject the Null Hypothesis


## ANOVA

## Question 4 

If you need to compare more than two data sets at a time, an ANOVA is your best bet. 

*The results from three experiments with overlapping 95% confidence intervals are given below, and we want to confirm that the results for all three experiments are not significantly different.*

But before conducting ANOVA, test equality of variances (using Levene's test) is satisfied or not. If not, then mention that we cannot depend on the result of ANOVA

In [423]:
import numpy as np

e1 = np.array([1.595440,1.419730,0.000000,0.000000])
e2 = np.array([1.433800,2.079700,0.892139,2.384740])
e3 = np.array([0.036930,0.938018,0.995956,1.006970])

#Assumption: All the 3 datasets (e1,e2 & e3) are random, independent, parametric & normally distributed

Perform levene test on the data

The Levene test tests the null hypothesis that all input samples are from populations with equal variances. Levene’s test is an alternative to Bartlett’s test bartlett in the case where there are significant deviations from normality.

source: scipy.org

#### Answer:

In [424]:
pval_levene = stats.levene(e1,e2,e3).pvalue
pval_levene

0.12259792666001798

In [425]:
print("P-Value is %5.2f"%(pval_levene))
print("%5.2f is not less than %5.2f" %(pval_levene, (5/100)))
print("Hence, we cannot depend on the result of ANOVA")

P-Value is  0.12
 0.12 is not less than  0.05
Hence, we cannot depend on the result of ANOVA


## Question 5

The one-way ANOVA tests the null hypothesis that two or more groups have the same population mean. The test is applied to samples from two or more groups, possibly with differing sizes.

use stats.f_oneway() module to perform one-way ANOVA test

In [426]:
pval_1anova = stats.f_oneway(e1,e2,e3).pvalue
pval_1anova

0.13574644501798466

In [427]:
print("Hence, we cannot reject the null hypothesis.")

Hence, we cannot reject the null hypothesis.


## Question 6

*In one or two sentences explain about **TypeI** and **TypeII** errors.*

#### Answer:

<b>Type1 Error:</b>
<p>Also called as <b>'False Positive'</b>, occurs when a Null Hypothesis is rejected when it is actually true.</p>

<b>Type2 Error:</b>
<p>Also called a <b>'False Negative'</b>, occurs when a Null Hypothesis is failed to be rejected, when it is actually false.</p>

## Question 7 

You are a manager of a chinese restaurant. You want to determine whether the waiting time to place an order has changed in the past month from its previous population mean value of 4.5 minutes. 
State the null and alternative hypothesis.

#### Answer:


<b>Null Hypothesis:</b> The population mean of waiting time is 4.5 mins. <br/>
<b>Alternate Hypothesis:</b> The population mean of waiting time is not 4.5 mins.

## Chi square test

## Question 8

Let's create a small dataset for dice rolls of four players

In [428]:
import numpy as np

d1 = [5, 8, 3, 8]
d2 = [9, 6, 8, 5]
d3 = [8, 12, 7, 2]
d4 = [4, 16, 7, 3]
d5 = [3, 9, 6, 5]
d6 = [7, 2, 5, 7]

dice = np.array([d1, d2, d3, d4, d5, d6])

run the test using SciPy Stats library

Depending on the test, we are generally looking for a threshold at either 0.05 or 0.01. Our test is significant (i.e. we reject the null hypothesis) if we get a p-value below our threshold.

For our purposes, we’ll use 0.01 as the threshold.

use stats.chi2_contingency() module 

This function computes the chi-square statistic and p-value for the hypothesis test of independence of the observed frequencies in the contingency table

Print the following:

- chi2 stat
- p-value
- degree of freedom
- contingency



In [429]:
chi2_stat, pval_chi2, dof_chi2, expec_chi2 = stats.chi2_contingency(dice)

In [430]:
print("The chi2 stat is: %5.2f"%chi2_stat)
print()
print("The P-Value is: %5.2f"%pval_chi2)
print()
print("The Degree of Freedom is: %5.2f"%dof_chi2)
print()
print("Contigency Table is: ")
print(expec_chi2)

The chi2 stat is: 23.32

The P-Value is:  0.08

The Degree of Freedom is: 15.00

Contigency Table is: 
[[ 5.57419355  8.20645161  5.57419355  4.64516129]
 [ 6.50322581  9.57419355  6.50322581  5.41935484]
 [ 6.73548387  9.91612903  6.73548387  5.61290323]
 [ 6.96774194 10.25806452  6.96774194  5.80645161]
 [ 5.34193548  7.86451613  5.34193548  4.4516129 ]
 [ 4.87741935  7.18064516  4.87741935  4.06451613]]


## Question 9

### Z-test

Get zscore on the above dice data using stats.zscore module from scipy. Convert zscore values to p-value and take mean of the array.

In [431]:
z_score_tab = stats.zscore(dice)
print("Z score is as shown below:")
print()
print(z_score_tab)

Z score is as shown below:

[[-0.46291005 -0.18884739 -1.83711731  1.44115338]
 [ 1.38873015 -0.64208114  1.22474487  0.        ]
 [ 0.9258201   0.7176201   0.61237244 -1.44115338]
 [-0.9258201   1.62408759  0.61237244 -0.96076892]
 [-1.38873015  0.03776948  0.          0.        ]
 [ 0.46291005 -1.54854863 -0.61237244  0.96076892]]


In [432]:
p_value = stats.norm.sf(z_score_tab)
print("P-Value is as shown below: ")
print()
print(p_value)

P-Value is as shown below: 

[[0.67828558 0.57489379 0.96690371 0.07477068]
 [0.08245741 0.73958975 0.11033568 0.5       ]
 [0.17726974 0.23649578 0.27014569 0.92522932]
 [0.82273026 0.05217856 0.27014569 0.83166582]
 [0.91754259 0.48493574 0.5        0.5       ]
 [0.32171442 0.93925487 0.72985431 0.16833418]]


In [433]:
print("Mean of P-Values is: %5.3f"%p_value.mean())

Mean of P-Values is: 0.495


## Question 10

A Paired sample t-test compares means from the same group at different times.

The basic two sample t-test is designed for testing differences between independent groups. 
In some cases, you might be interested in testing differences between samples of the same group at different points in time. 
We can conduct a paired t-test using the scipy function stats.ttest_rel(). 

In [434]:
before= stats.norm.rvs(scale=30, loc=100, size=500) ## Creates a normal distribution with a mean value of 100 and std of 30
after = before + stats.norm.rvs(scale=5, loc=-1.25, size=500)

Test whether a weight-loss drug works by checking the weights of the same group patients before and after treatment using above data.

In [435]:
# z_score_bf = abs(stats.zscore(before))
# p_value_bf = stats.norm.sf(z_score_bf)
# p_value_bf

In [436]:
# z_score_af = abs(stats.zscore(after))
# p_value_af = stats.norm.sf(z_score_af)
# p_value_af

In [437]:
# print(stats.ttest_rel(p_value_bf, p_value_af))
statistic_wl, pval_wl = stats.ttest_rel(before, after)
print("P-Value is %3.16f"%pval_wl)
print("We can reject the null hypothesis.")
print("Hence, the weight loss drug works..")

P-Value is 0.0000000000039444
We can reject the null hypothesis.
Hence, the weight loss drug works..
